const menu = [
  {
    id: 1,
    title: 'Special Jollof rice',
    category: 'lunch',
    price: 2999.99,
    img: '/images/rice_and_chicken.jfif',
    desc: `Order our special jolloF rice, with either coleslaw and or peppered chicken, turkey or beef and experience the best of tongue tingling explosion `,
  },
  {
    id: 2,
    title: 'Ronys fried rice',
    category: 'lunch',
    price: 2999.99,
    img: '/images/fried_rice_chicken.jpeg',
    desc: ` Order our special fried rice, salad, with peppered chicken, turkey or beef and experience worldclass food. Our combos are without equals`,
  },
  {
    id: 3,
    title: 'ronys fruity zobo',
    category: 'drinks',
    price: 999.99,
    img: '/images/item-3.jpeg',
    desc: `Taste our natural, organic zobo prepared in the most hygenic environment. Made with hiiscus and fruits with no artificial flavours .`,
  },
  {
    id: 4,
    title: 'Continental Delight',
    category: 'Lunch',
    price: 2499.99,
    img: '/images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Bassmati rice special',
    category: 'lunch',
    price: 3499.99,
    img: '/images/bassmati-rice.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: '/images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: '/images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: '/images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
